### ISSUE TITLE
reset keypress handler problem

### ISSUE THREAD

**Issue by cleeeem** [odyniec/imgareaselect#11]
Hi,

I suggest you to check if "$.imgAreaSelect.onKeyPress" exists before unbinding "keydown" event or it will also unbind all other handlers outside the plugin.

if ($.imgAreaSelect.keyPress != docKeyPress && typeof($.imgAreaSelect.onKeyPress) != 'undefined' )
   $(document).unbind($.imgAreaSelect.keyPress, $.imgAreaSelect.onKeyPress);

**Comment by odyniec** [comment]
I haven't been able to produce such a scenario, I think it shouldn't happen. Feel free to reopen this issue if you can demonstrate otherwise.

**Comment by virvum** [comment]
I can reproduce the problem.
