### ISSUE TITLE
imgAreaSelect Won't Clean Up After Itself, Creates Prior-Crop Artifacts 

### ISSUE THREAD

**Issue by mikeschinkel** [odyniec/imgareaselect#14]
I'll start by saying I could likely be doing something wrong in my code.  I've been fighting this project to literally 2 days, and this is just the latest issue I've run into.
### BACKGROUND:

I have an image uploader that is uploading an image within a WordPress admin post edit screen and I am using a jQuery FancyBox to display the image and imgAreaSelect v0.9.6 (which is the one provided by WordPress v3.2.)  My uploader is simple in that it allow the user to click upload and if they select an image it automatically pops up a resizing box and an image cropper.  if they click "save" the crop selection is written back into the HTML of the document as well as via AJAX back to the WordPress database. All that works great.
### PROBLEM:

However, if a user then clicks "delete" our code clears out the HTML where the image used to be but if the user uploads another image imgAreaSelect added it adds double the HTML and now I see remnants of previous cropper mask on the screen.  I've looked but I can't seem to find a way to get imgAreaSelect to actually clean up it's HTML after I delete an image.
### EXAMPLE:

Here's what the problem looks like after displaying the crop window for the first photo, deleting it, then uploading a new image and displaying the crop window for it. Note that is keep doubling opacity:

![Problem with remnant imgAreaSelect cropping](http://screenshots.newclarity.net/skitched-20111120-211212.jpg)
### WORKAROUND:

I've managed to get the following code to work, but of course it is very fragile and will stop working if the HTML used is changed and WordPress upgrades to the newer version:

```
$(".imgareaselect-selection").parent().remove();
$(".imgareaselect-outer").remove();
```
### SUGGESTIONS?

Minimally it would have been nice of the HTML could have been wrapped by on `<div>` with one `id` and I could have just deleted it all.  
### A BETTER WAY?

Like I said, I could be doing this wrong, so if there is an obvious thing I missed that I can do with v0.9.6 then please let me know a better way.  Thanks in advance.

**Comment by odyniec** [comment]
I don't expect you to still be waiting for help with this issue, considering that it's a year old (yeah, that's how awful I am in responding in a timely manner, sorry) -- but if you do, please contact me by e-mail.

**Comment by DanielJoyce** [comment]
Still a bug in latest version. Annoying.

**Comment by DanielJoyce** [comment]
Jquery UI defines widget methods and an api just for this reason. Should not be littering the dom with garbage when I ask it to remove itself.

**Comment by bradvogel** [comment]
I see you have the `remove()` method now. Thanks!

**Comment by adnanhaider80** [comment]
I have bootstrap modal on modal opening previously uploaded a picture will be shown selected coordinates.
Remove method is not working (version 0.9.11-rc.1).

**Comment by franscronje** [comment]
I'm from the South African Post Office and we need to let clients upload a mail document in PDF.  I would like the client to select the Address Area so that I can get the X Y and size dimensions to do a PDF-to-Text extract.  I'm unable to get imagAreaSelect to work with a PDF.  Can you help?

> $(document).ready(function () {
>     $('img#fred2').imgAreaSelect({ 
> 		imageHeight: 1100, imageWidth: 850, handles: true 
> 	});
> });
> </script>
> 	
> 		<div class="container">
> 		<iframe id="fred2" style="border:1px solid #666CCC" title="PDF in an i-Frame" src=<?php echo ($xfile) ?> frameborder="1" scrolling="auto" height="1100" width="850" ></iframe>
> 		</div>
> 		

[Doc2.pdf](https://github.com/odyniec/imgareaselect/files/1456535/Doc2.pdf)

**Comment by sohaib12296** [comment]
![image](https://user-images.githubusercontent.com/58909853/73091540-74c57600-3efc-11ea-882a-e9b561175ff3.png)

this is what happened with me it is completely black not opaque
