### ISSUE TITLE
some syntax issues

### ISSUE THREAD

**Issue by xiaojue** [odyniec/imgareaselect#16]
https://github.com/odyniec/imgareaselect/blob/master/jquery.imgareaselect.dev.js#L921

https://github.com/odyniec/imgareaselect/blob/master/jquery.imgareaselect.dev.js#L959

https://github.com/odyniec/imgareaselect/blob/master/jquery.imgareaselect.dev.js#L961

(o =) can be write like this:

if (options.borderColor1)
            $($border[0]).css({ borderStyle: 'solid', borderColor: options.borderColor1 });
        if (options.borderColor2)
            $($border[1]).css({ borderStyle: 'dashed', borderColor: options.borderColor2 });

some other issues is this too.

**Comment by odyniec** [comment]
Thanks for your feedback, but that was intentional and is going to stay :)
