### ISSUE TITLE
if (o = options.borderWidth)

### ISSUE THREAD

**Issue by paazmaya** [odyniec/imgareaselect#18]
Line 921 has the following line:

 if (o = options.borderWidth)

Perhaps it should be == instead of =

**Comment by AaronLasseigne** [comment]
The line is correct. It will set `o` and return the value from `options.borderWidth` so the `if` can check it. It's the same as:

``` javascript
o = options.borderWidth
if (o)
  $handles.css({ borderWidth: o, borderStyle: 'solid' });
```

**Comment by paazmaya** [comment]
Would it make sense for readability to change the line to the one you commented in the reply?

**Comment by AaronLasseigne** [comment]
Perhaps, but I think that's subjective. I suspect odyniec (the author) likes the style he's used. It would be up to him to change it.

**Comment by odyniec** [comment]
Actually, I'm using constructs like this to save a few bytes here and there (this can make a significant difference when the code gets packed/minified). I usually prefer cleaner code, like the one that @AaronLasseigne demonstrated :-)
