### ISSUE TITLE
IE9 Selection Box

### ISSUE THREAD

**Issue by ellemayo** [odyniec/imgareaselect#2]
It appears the selection box in IE9 has some issues. Whenever selecting, it jumps between the boundaries and the actual selection box.

**Comment by sewpafly** [comment]
I was seeing this issue as well (It's using an older version of the plugin because it's what ships with wordpress 3.1).  However wordpress' implementation doesn't seem to have the same bug.  Do you know what the work around might be?

**Comment by sewpafly** [comment]
My problem appears to have been calling console.log in IE. I apologize.

**Comment by ellemayo** [comment]
This issue appears to have been fixed in an IE update... not sure what the version number of the problematic IE was
