### ISSUE TITLE
Problem with Jquery 1.8.1 & IE9

### ISSUE THREAD

**Issue by Delpak** [odyniec/imgareaselect#22]
when i update Jquery to 1.8.1 plugin works fine on Chrome & FF but i face errors on IE9.
but when i commented this codes , plugins works again!

in file jquery.imgareaselect.js line line 608 comment codes below:

//        if ($.browser.msie) {
//            if (o = $outer.css('filter').match(/opacity=(\D(\d+))/))
//                $outer.css('opacity', o[1]/100);
//            if (o = $border.css('filter').match(/opacity=(\D(\d+))/))
//                $border.css('opacity', o[1]/100);
//        }

this solve my problem!

**Comment by lingej** [comment]
I can confirm this.
Cheers Joerg

**Comment by odyniec** [comment]
Thanks for reporting, this is now fixed in the development version.

**Comment by rgriffith** [comment]
I am not sure if this is related, but I am running into an issue in IE8 where the inline `filter:` style applied to `.imgareaselect-outer` is empty, causing them to be solid black. Using jQuery 1.7.2 and the latest plugin version.
