### ISSUE TITLE
IE9 + jQuery 1.8.2

### ISSUE THREAD

**Issue by davidmles** [odyniec/imgareaselect#24]
When using IE9 + jQuery 1.8.2 (currently the latest version) it does not work. It works with no problems on IE7 and IE8.

The image appears, but no selection can be made.

**Comment by odyniec** [comment]
Do you still have this issue with the current development version (the one here on GitHub)?

**Comment by davidmles** [comment]
I don't know, because I made my own version from scratch. Sorry.
