### ISSUE TITLE
minWidth & minHeight

### ISSUE THREAD

**Issue by loa** [odyniec/imgareaselect#3]
Hey!!

Really nice utility. Thanks alot for your effort.

Anyways, I'm trying to crop pictures where I want a fixed aspect ratio and minimal height and width on the result image after crop. And as I will handle really big pictures I found imageHeight and imageWidth properties to be very usefull.

My issue is that I thought that minWidth and minHeight would scale along with the picture so the minimum values would be the resulting selected area of the picture but isnt. It's plainly the size of the selection window.

Is this working as intended? Missing feature? Would you want a minResWidth and minResHeight implemented?

Sincere yours Loa

**Comment by loa** [comment]
Resolved my issue by implementing the missing feature. Pull request here #4

**Comment by odyniec** [comment]
Thanks for your feedback. I didn't really give much thought to min/max dimensions when I added the imageWidth/Height options, and I guess they should scale along, as you say. So I'll probably implement it this way in the next release. I think it would be a better solution that adding several new options.

**Comment by loa** [comment]
How much have you thought about changing / adding for next release?

I want to use this plugin for a website I'm maintaining and it feels better to help out on the official plugin than creating my own unofficial fork. If you have stuff that you want changed but don't have time or effort to put on it right now then just tell and I can help you out.

**Comment by odyniec** [comment]
I'm going to publish a basic roadmap in the next couple of days -- I have a few minor changes planned for the next 0.9.x release, and a couple more significant updates for version 1.0. If you could help with some of the changes, that would be great. I'll let you know when the roadmap is ready.

**Comment by loa** [comment]
Sounds great

**Comment by lukearmstrong** [comment]
I was going to add this as an issue.

I started setting this up, and was very pleased to find the imageWidth and imageHeight to allow scaling, and even more amazed that the x1/y1/x2/y2 took into consideration the scaling and provided my backend script with accurate values. Then I went on to set the minWidth and minHeight and they didn't work as I had expected. IMHO the minWidth and minHeight should behave in the same way that the x1/y1/x2/y2 does in that it takes into account the scaling.

For now I am going to try using the onSelectChange callback to enforce a minimum width and height, by forcing the x2 and y2 to be at least (x1 + myMinWidth) and (y1 + myMinHeight).

Great plugin btw. I am now on my 3rd JS crop tool. I started out with jCrop, but it crashes the browser when making selections on large scaled images, and generally runs slow. Then I found Uvumi Tools Crop, but during our latest round of testing it doesn't work in IE9. Neither projects have been updated in 2 years, and have died. Thanks again for creating this plugin, and putting it on Github (where I initially found it).

**Comment by loa** [comment]
@lukearmstrong do notice that I already fixed it. Just that odyniec wants to change the current min/max values to scale instead of adding the settings that I did. Just grap the source at #4.

**Comment by lukearmstrong** [comment]
@Loa I am going to try that now as my proposed method turned out to be a bit buggy, and appears to make the crop tool operate less smoothly. Thanks for the fork.

**Comment by lukearmstrong** [comment]
@Loa Downloaded your dev script from your fork because I didn't know if you had updated the packed/minified version, and it works perfectly. Cheers.

**Comment by odyniec** [comment]
The min/max options now properly handle scaled images.
