### ISSUE TITLE
Question: selection coordinates

### ISSUE THREAD

**Issue by xfra35** [odyniec/imgareaselect#34]
Hi,

Thanks for your work. This plugin is a very useful tool !

I have a question regarding the selection coordinates returned by the plugin. I'm not sure if there is a bug or if I'm missing something.
When we get the coordinates of a selection, it seems to me that x2 and y2 are 1px higher than they should be.

For example, in the case where we update a form using the callback onSelectEnd as in [this demo](http://odyniec.net/projects/imgareaselect/examples-callback.html#submitting-selection-coordinates-demo), considering we select the whole image (which is 400x300px), we get the following coordinates :
x1: 0
y1: 0
x2: 400
y2: 300

Shouldn't x2 and y2 be 399 and 299 ? (otherwise the overall width & height would be 401x301 px)

**Comment by odyniec** [comment]
Yes, you are right -- this was a mistake I made in an early version of the plugin, I noticed it later but decided not to change the behavior of the code to maintain backwards compatibility. Now that I'm about to release version 1.0 which won't be constrained by this, I can finally fix this issue.

(And sorry for answering this four months late... I'm awful.)
