### ISSUE TITLE
$.broswer is gone from jQuery 1.9

### ISSUE THREAD

**Issue by AndrewPenry** [odyniec/imgareaselect#36]
Which means imgareaselect no longer works. I mitigated this by using just the $.broswer parts of the jquerymigrate plugin, but imgareaselect may want to use something else for doing some of its browser switching.

**Comment by natatkinson** [comment]
Any plans to fix this?

EDIT: sorry, see you already fixed this. THANK YOU!

**Comment by odyniec** [comment]
Actually, this was already fixed in commit 98fc34805a6a371962f150f111807ea8b8a30fbd. Closing the issue now.

(I'm currently working on a new release and I'll try to go through all the open issues to clean up the list.)
