### ISSUE TITLE
Overlay remains visible after switching tabs in Jquery UI Tabs

### ISSUE THREAD

**Issue by WRidder** [odyniec/imgareaselect#5]
When using the Tabs  from Jquery UI and adding ImgAreaSelect to e.g. the second tab there is a problem when you select an area and then switch tabs. Instead of hiding the darkened overlay + selection it remains on top of the other tabs. 

Switched to ImgAreaSelect from Jcrop. IAS suits me more, but this bug is a bit annoying. 

On a side note: the disable option doesn't seem to be working.

**Comment by odyniec** [comment]
Have you tried setting the tab as the parent element, using the `parent` option? This might resolve the problem.

**Comment by WRidder** [comment]
That almost fixes it! Although the overlay isn't shown anymore when selecting a tab other than the one IAS is residing on, there is a problem now with the overlay and selector.

Check the following image: http://imageshack.us/photo/my-images/827/tabsimgareaselect.png/

As you can see, now it is misplaced.

**Comment by ahoek** [comment]
I encountered the same problem, if you add 'position: relative' to the parent, the overlay is placed correctly and is not show on other tabs.
