### ISSUE TITLE
resize after change photo not possible (chrome only ?)

### ISSUE THREAD

**Issue by dcz-switcher** [odyniec/imgareaselect#7]
Thanks for your excellent plugin

os : mac os
browser : Google Chrome 11 (works fine on Firefox 4)
imageAreaSelect : 0.9.6
jquery : 1.6.1

I try to use it with uploadify, everythings work fine instead when I uploaded a new image and change the photo src with jQuery attr : I can't resize the selection, just move it  ?!?

So, I clic anywhere out of the page (browser's menu, another window ...) or, just put the cursor over web browser menu and it works !

maybe a focus problem

better with an exemple : http://luma79.com/labs/crop_upload/
1. make a selection and clic "crop" button
2. select a photo from your hardrive
3. try to make and resize the selection on the new photo //it doesn't works on Google Chrome
4. clic on another window (page lost focus)
5. resize the selection area //it works !

important : works fine on Firefox, only detected on Google Chrome

thanks again to share your work

**Comment by odyniec** [comment]
@davtwix: Sorry for the delay in getting back to you on this. I couldn't reproduce the issue using the example you provided, I tried today with the latest release of Chrome in Ubuntu and Mac OS X. Have you by any chance implemented a workaround for that example?

**Comment by dcz-switcher** [comment]
Thanks to reply,

No, I did nothing but I think I understand the problem while tried to record my screen to share a video of it : 
I use a macbook pro with external screen, if the navigator window is on macbook screen, no problem, but if I used the external one, I have the problem ????

sorry, the problem is not with your awesome plugin !

thanks again
