### ISSUE TITLE
Wrong placement in Google Chrome

### ISSUE THREAD

**Issue by iGrog** [odyniec/imgareaselect#8]
Hi.

I have some problems in Google Chrome.

![Example 1](http://grog13.dyndns.org/e2.jpg)

When I scroll page vertically and show imgAreaSelect again, it's in different place.

![Example 1](http://grog13.dyndns.org/e1.jpg)

In other browsers all OK. 
Can you help me? Thanks :)

**Comment by odyniec** [comment]
@iGrog: Can you show me the actual website that has this problem?

**Comment by iGrog** [comment]
Yes, try this: solved
(scroll to first comment and press 'show' link)

This is my home comp, internet speed may be slow. Thanks for fast answer.

**Comment by odyniec** [comment]
I'm not sure why this only happens in Chrome, but this is clearly a positioning problem -- using the `parent` option and setting it to `'.page'` should help. A similar problem is described in the FAQ: http://odyniec.net/projects/imgareaselect/faq.html#faq-3

**Comment by iGrog** [comment]
Thanks a lot.
I've not noticed this FAQ section. It's really helped :)
